# Example agpod kiro configuration
# Place this at ~/.config/agpod/config.toml or .agpod.toml in your project root

base_dir = "llm/kiro"
templates_dir = "~/.config/agpod/templates"
plugins_dir = "~/.config/agpod/plugins"
template = "default"
summary_lines = 3

[plugins.name]
enabled = true
command = "name.sh"
timeout_secs = 3
pass_env = ["AGPOD_*", "GIT_*", "USER", "HOME"]

[rendering]
files = ["DESIGN.md.j2", "TASK.md.j2"]
extra = []
missing_policy = "error"

# Template-specific configurations
[templates.default]
description = "Standard PR draft template with design and task documents"
files = ["DESIGN.md.j2", "TASK.md.j2"]
missing_policy = "error"

[templates.vue]
description = "Vue.js component development template"
files = ["DESIGN.md.j2", "TASK.md.j2", "COMPONENT.md.j2"]
missing_policy = "skip"

[templates.rust]
description = "Rust implementation template with detailed design"
files = ["DESIGN.md.j2", "TASK.md.j2", "IMPL.md.j2"]
missing_policy = "error"
